### ISSUE TITLE
Not detecting forge

### ISSUE THREAD

**Issue by fusionmc-evilscoop** [kremi151/ForgedPerms#1] opened 2017-08-23 08:49 UTC
23.08 03:47:28 [Server] Server thread/ERROR [FML]: The mod forgedperms (ForgedPerms) requires mods [forge] to be available 23.08 03:47:28 [Server] Server thread/ERROR [FML]: Mod forgedperms (ForgedPerms) requires [forge] 23.08 03:47:28 [Server] Server thread/ERROR Encountered an unexpected exception 23.08 03:47:28 [Server] INFO net.minecraftforge.fml.common.MissingModsException: Mod forgedperms (ForgedPerms) requires [forge] 23.08 03:47:28 [Server] INFO Missing Mods: 23.08 03:47:28 [Server] INFO forge : any

forge-1.10.2-12.18.3.2316-universal.jar
SpongeBootstrap-0.4.0.jar (needed to fix core mod injection for ae2)
spongeforge-1.10.2-2281-5.2.0-BETA-2597.jar

**Comment by kremi151** [comment] 2017-08-23 09:31
This issue should be fixed by the mentioned commit. I will upload the new version to the Ore platform. Make sure to take the version dedicated to Minecraft 1.10.2

**Closed as completed** 2017-08-23 09:31 UTC
Labels: bug

**Comment by fusionmc-evilscoop** [comment] 2017-08-23 09:45
Same issue from sponge ore 
1.0.0.2 (For Minecraft 1.10.2)
File size not changed... wrong one uploaded as its the same filename
ForgedPerms.jar (might wanna put a version in the filename :D )

23.08 05:43:34 [Server] Server thread/ERROR Encountered an unexpected exception 23.08 05:43:34 [Server] INFO net.minecraftforge.fml.common.MissingModsException: Mod forgedperms (ForgedPerms) requires [forge] 23.08 05:43:34 [Server] INFO Missing Mods: 23.08 05:43:34 [Server] INFO forge : any 23.08 05:43:34 [Server] INFO at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266) ~[Loader.class:?] 23.08 05:43:34 [Server] INFO at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:536) ~[Loader.class:?] 23.08 05:43:34 [Server] INFO at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?] 23.08 05:43:34 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) ~[FMLCommonHandler.class:?] 23.08 05:43:34 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[ld.class:?] 23.08 05:43:34 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?] 23.08 05:43:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by kremi151** [comment] 2017-08-23 09:52
Are you sure you downloaded the correct version? Because the right version should not search for "forge" in lowercase but for "Forge" in uppercase

**Comment by kremi151** [comment] 2017-08-23 09:53
Oh forget what I'm saying, I see what the problem is :/

**Comment by fusionmc-evilscoop** [comment] 2017-08-23 09:53
downloaded 3 times from https://ore.spongepowered.org/kremi151/ForgedPerms/versions/1.0.0.2%20(For%20Minecraft%201.10.2)
all do the same

**Comment by kremi151** [comment] 2017-08-23 09:54
I will try to rename the jar files, this might fix this problem

**Comment by kremi151** [comment] 2017-08-23 10:08
Well I uploaded it with different file names on ore. Please try if you can download it because it does not work for me. If that's the case, please let me know. This is definitetly a problem of Sponge Ore...

**Comment by fusionmc-evilscoop** [comment] 2017-08-23 10:14
Looking good now -
[forgedperms]: Forge permission API has been linked to the permission service of class me.lucko.luckperms.sponge.service.proxy.api6.PermissionServiceProxy from plugin luckperms

**Comment by kremi151** [comment] 2017-08-23 10:17
Seems like it is finally working now. I'm glad I could help.
